### ISSUE TITLE
'TO BE ANNOUNCED' & 'TBA' Alignment

### ISSUE THREAD

**Issue by RGTechPro** [MicrosoftStudentChapter/makeathon_2021#40]
### **'TO BE ANNOUNCED' & 'TBA' (Prize section) not center aligned in screensizes greater than 1000.**
![Screenshot_656](https://user-images.githubusercontent.com/73791635/149618807-8502664d-889f-4e27-964e-9e7ebb2d54e1.png)

**Comment by destrex271** [comment]
I can work on it

**Comment by nimishmedatwal** [comment]
i can work on it
